export const CONFIG = {
    'URL': {
        // 'BASE': 'https://apis.digirekord.com/api/',
        'BASE': 'http://localhost:3000/api/',
        'LOGIN': 'users/login',
        'CHECK_USER_EXISTS': 'users/checkUserExist',
        'GET_ALL_FEATURES': 'institute/getAllFeatures',
        'GET_TIME_ZONES': 'institute/getTimeZones',
        'GET_ALL_INSTITUTE': 'institute/getInstituteCount',
        'CREATE_INSTITUTE': 'institute/createInstitute',
        'UPDATE_INSTITUTE': 'institute/updateInstitute',
        'GET_INSTITUTE_DETAIL': 'institute/getInstituteDetails',        
        'ADD_SMS_CREDITS': 'institute/addSMSCredits',        
        'SAVE_SMS_DETAILS': 'institute/saveSMSAccountDetails',        
        'GET_ALL_SCHOOL': 'school/getSchoolsList',
        'CREATE_SCHOOL': 'school/createSchool',
        'GET_SCHOOL_DETAIL': 'school/getSchoolDetails',
        'UPDATE_SCHOOL': 'school/updateSchool',
        'GET_ALL_CLASSES': 'setUp/classes',
        'CREATE_CLASS': 'institute/createClass',
        'UPDATE_CLASS': 'institute/updateClass',
        'CREATE_SUBJECT': 'institute/createSubject',
        'UPDATE_SUBJECT': 'institute/updateSubject',
        'GET_ALL_STAFFS': 'staff/getStaffList',
        'CREATE_STAFF': 'staff/createStaff',
        'UPDATE_STAFF': 'staff/updateStaff',
        'GET_STAFF_DETAIL': 'staff/getStaffDetails',
        'ASSIGN_CLASS_SUBJECT': 'school/assignClassesSubjects',
        'ASSIGN_STAFF_CLASS': 'staff/assignSubjects',
        'GET_ALL_STUDENT': 'student/getStudentsList',
        'CREATE_STUDENT': 'student/createStudent',
        'GET_STUDENT_DETAIL': 'student/getStudentDetails',
        'UPDATE_STUDENT': 'student/updateStudent',        
        'SAVE_SETTINGS': 'student/saveSettings',    
        'ADD_FEE': 'student/addFee',
        'COMPOSE_MESSAGE': 'messages/composeMessage',        
        'SND_SMS': 'messages/sendSMS',        
        'SND_SMS_FOR_ABSENT': 'attendance/sendSMSForAbsenties',
        'GET_ALL_CLASS_STUDENTS': 'student/getStudentsFromStaff',
        'GET_ALL_MESSAGES': 'messages/getMessages',
        'GET_ALL_LEAVES': 'leaveManagement/getLeaves',
        'APPLY_LEAVE': 'leaveManagement/applyLeave',
        'DELETE_STUDENT': 'student/deleteStudent',
        'DELETE_STAFF': 'staff/deleteStaff',
        'DELETE_SCHOOL': 'school/deleteSchool',
        'APPROVE_REJECT_LEAVE': 'leaveManagement/approveLeave',
        'GET_STAFF_ROLES': 'staff/getStaffRoles',
        'GET_STAFF_LEAVES': 'staff/getLeaves',
        'APPLY_STAFF_LEAVE': 'staff/applyLeave',
        'APPROVE_REJECT_STAFF_LEAVE': 'staff/approveLeave',
        'DELETE_INSTITUTE': 'institute/deleteInstitute',
        'GET_STATES': 'school/getStates',
        'GET_DISTRICTS': 'school/getDistricts',
        'GET_ACADEMIC_YEARS': 'school/getAcademicYears',
        'GET_STUDENTS_FOR_ATTENDANCE': 'student/getStudentsForAttendance',
        'CREATE_ATTENDANCE': 'student/createAttendanceReport',
        'GET_OVERALL_ATTENDANCE': 'student/getOverallAttendanceReport',
        'GET_STUDENT_ATTENDANCE_DETAIL': 'student/getDetailedAttendanceReport',
        'CREATE_GALLERY': 'school/createGallery',
        'GET_GALLERY': 'school/gallery/getImages',
        'LIKE_GALLERY_IMAGE': 'school/gallery/addLike',
        'COMMENT_GALLERY_IMAGE': 'school/gallery/addComment',
        'DELETE_GALLERY_IMAGE': 'school/gallery/deleteImage',
        'DELETE_GALLERY_IMAGE_COMMENT': 'school/gallery/deleteComment',
        'CREATE_ACHIEVEMENT': 'school/acheivements/createAcheivement',
        'GET_ACHIEVEMENT': 'school/acheivements/getAcheivements',
        'LIKE_ACHIEVEMENT': 'school/acheivements/addLike',
        'COMMENT_ACHIEVEMENT': 'school/acheivements/addComment',
        'DELETE_ACHIEVEMENT_COMMENT': 'school/acheivements/deleteComment',
        'DELETE_ACHIEVEMENT_ATTACHMENT': 'school/acheivements/deleteAttachment',
        'DELETE_ACHIEVEMENT': 'school/acheivements/deleteAcheivement',
        'DELETE_STAFF_ATTACHMENT': 'staff/deleteAttachment',
        'DELETE_MESSAGE_ATTACHMENT': 'messages/deleteAttachment',
        'DASHBOARD_WIDGET': 'dashboard/widget',
        'DASHBOARD_FEE_DETAILS': 'dashboard/getfeeDetails',
        'DASHBOARD_TOTAL_ATTENDANCE': 'school/dashboard/schoolAttendance',
        'DASHBOARD_MONTH_WISE_ATTENDANCE': 'dashboard/monthWiseAttendance',
        'INSTITUTE_DASHBOARD_WIDGET': 'institute/dashboard/widget',
        'PARENT_TOTAL_ATTENDANCE': 'parent/dashboard/fullYearAttendance',
        'PARENT_MONTH_WISE_ATTENDANCE': 'parent/dashboard/monthWiseAttendance',
        'GET_USER_PROFILE': 'users/getProfile',
        'UPDATE_PARENT_PROFILE': 'users/updateProfile',
        'UPDATE_USER_PASSWORD' : 'users/updatePassword',
        'INSTITUTE_CREATE_TERM': 'institute/createTerm',
        'INSTITUTE_UPDATE_TERM': 'institute/updateTerm',
        'SCHOOL_ASSIGN_TERMS': 'school/assignTerms',
        'CREATE_SUBJECT_DIVISION': 'school/terms/createSubjectDivision',
        'GET_ALL_SUBJECT_DIVISION': 'school/terms/getSubjectDivisions',
        'UPDATE_SUBJECT_DIVISION':'school/terms/updateSubjectDivision',
        'DELETE_SUBJECT_DIVISION': 'school/terms/deleteSubjectDivision',
        'GET_SUBJECT_MARKS_CARD': 'school/reports/getSubjectMarksReport',
        'ASSIGN_MARKS_CARD': 'school/reports/assignMarks',
        'GET_REPORTS_REMARKS': 'school/reports/getRemarks',
        'STUDENT_MARKS_REPORT': 'school/reports/studentMarksReport',
        'ASSIGN_REPORTS_REMARKS': 'school/reports/assignRemarks',
        'SETUP_HALLTICKETS': 'school/halltickets/setupHallTicket',
        'GET_HALLTICKET': 'school/halltickets/getHallTickets',
        'GET_EXCEL_ATTRIBUTES': 'school/customSMS/getExcelAttributes',
        'GET_PREVIEW_SMS': 'school/customSMS/getPreviewSMS',
        'GET_SMS': 'school/customSMS/getSMS',
        'SEND_SMS': 'school/customSMS/sendSMS',
        'GET_CLASS_ATTENDANCE_PIE': 'school/reports/getFullAttendanceForClass',
        'GET_CLASS_ATTENDANCE_BAR': 'school/reports/getMonthAttendanceForClass',
        'GET_CLASS_ATTENDANCE_STUDENTS': 'school/reports/getFullAttendanceForStudent',        
        'GET_ALL_SUBJECTMARK_SHEET': 'school/reports/getAllSubjectMarksSheet',        
        'GET_ALL_SUBJECTDIVISIONMARK_SHEET': 'school/reports/getAllSubjectDivisionMarksSheet', 
        'GET_SUBJECTWISEMARK_SHEET': 'school/reports/getSubjectWiseMarksSheet', 
        'GET_TOTALMARKS_FOR_STUDENTS': 'school/reports/getTotalMarksForStudents',
        'GET_FEETYPES': 'school/fees/getFeeTypes',
        'CREATE_FEETYPE': 'school/fees/addFeeType',
        'UPDATE_FEETYPE': 'school/fees/updateFeeType',
        'GET_FEETERMS': 'school/fees/getFeeTerms',
        'CREATE_FEETERM': 'school/fees/addFeeTerm',
        'UPDATE_FEETERM': 'school/fees/updateFeeTerm',
        'GET_FEES': 'school/fees/getFees',
        'CREATE_FEE': 'school/fees/addFees',
        'UPDATE_FEE': 'school/fees/updateFees',
        'ASSIGN_FEES_CLASSWISE': 'school/fees/assignFeesClasswise',
        'GET_ASSIGNED_FEE_CLASSWISE': 'school/fees/getAssignedFeesClasswise',
        'GET_ASSIGNED_FEE_STUDENTWISE': 'school/fees/getAssignedFeesStudentwise',
        'COLLECT_FEE': 'school/fees/collectFee',
        'GET_FEE_PAYMENTS': 'school/fees/getStudentFeePayments',
        'GET_FEE_TRANSACTIONS': 'school/fees/getStudentFeeTransactions',
        'ASSIGN_FEE_STUDENTWISE': 'school/fees/assignFeeStudentwise',
        'GET_SUMMARY_REPORT': 'school/fees/getSummaryReport',
        'GET_TREND_REPORT': 'school/fees/getTrendReport',
        'GET_FEE_REPORT': 'school/fees/getReports'
    },
    'MSG': {
        'appTitle': 'Institute management system',
        'invalid_logo_file_type': 'Please upload valid file, Accept only png, jpeg, jpg...',
        'invalid_logo_file_size': 'Please upload valid file, Accept only Max 1MB file...',
    },
    'ROUTES': {
        'LOGIN': 'login',
        'PRIVATE': 'private',
        'DASHBOARD': 'dashboard',
        'INSTITUTE': 'institutes',
        'INSTITUTE_PROFILE': 'instituteProfile',
        'SCHOOL_MGMT': 'schools',
        'WELCOME': 'welcome',
        'ACADEMIC_SETUP': 'academicSetUp',
        'STAFF': 'staff',
        'STUDENT': 'student',
        'TIMELINE': 'timeline',
        'LEAVE_MGMT': 'leaves',
        'ATTENDANCE': 'attendance',
        'MY_LEAVES': 'myleaves',
        'LEAVES_FOR_APPROVE': 'leavesforapprove',
        'GALLERY': 'gallery',
        'ACHIEVEMENTS': 'achievements',
        'PROFILE':'profile',
        'MARKS':'marks',
        'SUBJECT_DIVISION': 'division',
        'STUDENT_MARKS': 'submit',
        'STUDENT_REMARKS': 'remarks',
        'MARKS_CARD': 'card',
        'TRANSPORT': 'transport',
        'BUSES': 'buses',
        'ROUTES': 'routes',
        'HALLTICKETS': 'halltickets',        
        'HT_CONFIG': 'configurations',      
        'HT_STUDENTS': 'students',
        'CUSTOM_SMS': 'bulksms',
        'REPORTS': 'reports',
        'FEE_REPORT': 'fee',
        'ATTENDANCE_REPORT': 'attendance',
        'MARKS_REPORT': 'exams',
        'FEE_MGMT': 'fee-mgmt',        
        'FEE_SETUP': 'fee-setup',
        'FEE_ASSIGNMENTS': 'feesassignments',
        'FEE_COLLECTIONS': 'feescollections',
        'FEE_REPORTS': 'feesreports'
    },
    'ROLES': {
        'SUPER_ADMIN': 'superAdmin',
        'INSTITUTE_ADMIN': 'instituteAdmin',
        'SCHOOL_ADMIN': 'schoolAdmin',
    },
    'LOGO_MAX_SIZE': 1024000,
    'LOGO_FILE_TYPE': ['image/png', 'image/jpeg', 'image/jpg'],
    'YEARS': ['All', 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026],
    'MONTHS': [
        { key: 12, value: 'All' },
        { key: 0, value: 'January' },
        { key: 1, value: 'February' },
        { key: 2, value: 'March' },
        { key: 3, value: 'April' },
        { key: 4, value: 'May' },
        { key: 5, value: 'June' },
        { key: 6, value: 'July' },
        { key: 7, value: 'August' },
        { key: 8, value: 'September' },
        { key: 9, value: 'October' },
        { key: 10, value: 'November' },
        { key: 11, value: 'December' },
    ]
};
